### ISSUE TITLE
Error monitors

### ISSUE THREAD

**Issue by ChrisHird** [OSSILE/RelicPackageManager#14]
Some errors such as create library fail when the library already exists, how will your script processor allow those messages to be monitored for and ignored? maybe add a pre-amble such as IGNORE(CFP2103,CPF2105)  - SCRIPT('CRTLIB     LIB(&INTOLIB)') ? your call to QCMDEXEC can have a monitor that returns any messages and determines if they can be ignored?

**Comment by WorksOfBarry** [comment]
Hi! Thanks for raising this issue.

Currently, whenever a command failed it will print the error code from the command and carry on processing the build file.

Screenshot attached.

![image](https://cloud.githubusercontent.com/assets/3708366/15723098/c52f1b16-2838-11e6-91bc-51b0f3ebe2fe.png)

**Comment by WorksOfBarry** [comment]
Hi @ChrisHird 

Are you asking for functionality similar to CLs `monmsg` but within a build file?

Thanks,
Liam

**Comment by WorksOfBarry** [comment]
@ChrisHird Please see the functionality that has added the `monmsg` section - mentioned [in the wiki here](https://github.com/Club-Seiden/RelicPackageManager/wiki/Relic-Build-file).

Please let me know what you think, or close this bug when feel is ready.
