### ISSUE TITLE
Path to build file after unzip

### ISSUE THREAD

**Issue by ChrisHird** [OSSILE/RelicPackageManager#24]
Need to resolve the issue where the package manager is hard coding the current working directory as /home/USRPRF. You should use https://www.ibm.com/support/knowledgecenter/ssw_ibm_i_72/apis/getpwnam.htm (getpwnam() API) to retrieve the working path for the user profile and set accordingly. A number of people have stumbled over this already.

**Comment by ChrisHird** [comment]
Liam, here is some c code I use when building profile create strings.
pd = getpwnam(New_Prf);
if(pd == NULL) {
   /* no directory just return */
   sprintf(msg_dta,"%s",strerror(errno));
   snd_msg("GEN0001",msg_dta,strlen(msg_dta));
   return 1;
   }
else {
   strcat(Command," HOMEDIR('");
   strcat(Command,pd->pw_dir);
   strcat(Command,"')");
   }

**Comment by WorksOfBarry** [comment]
Hi @ChrisHird - thanks for raising this.

I understand that it had caused an issue with a few people now (you and @getfoundational), but it should be fixed.

All I had to do with remove the hard-code of the users home directory - then it will work with whatever the users real current directory is.

The relevant commit is fc8960321e5256bd01c319aa9c6e3a7b4710d163.

You can either rebuild from the master of the repo, or this patch will be available in Relic 0.006

Please close when you feel necessary. :)

**Comment by ChrisHird** [comment]
Liam

My preference would be to allow the root to be set, not force it into the users home directory. That way if you are required to install Open Source in a specific root you can manage that without going to your profile and setting it there before running the commands then changing it back.  Make sense?

**Comment by ChrisHird** [comment]
Another thought, think about the consequences of deleting a user profile, you could delete all of the downloaded source??

**Comment by WorksOfBarry** [comment]
Okay @ChrisHird 

Perhaps we could add an extra parameter so the user could chose where to store the ZIP and source?

**Comment by WorksOfBarry** [comment]
Looks like this issue has been fixed for a while.

You can now simple change your current directory and the package will be downloaded and unzipped there.

I will now close this issue.
