### ISSUE TITLE
Improve build file generation tool

### ISSUE THREAD

**Issue by ChrisHird** [OSSILE/RelicPackageManager#25]
Liam,

Having done 2 build files it would be nice to have a build tool that would scan a library for any source files and create the copy commands in a build file. Maybe front end with a command that takes any other variables you are going to allow at the same time?

**Comment by WorksOfBarry** [comment]
Hi @ChrisHird 

Perhaps you should take a look at the SYNC tool which is part of this repo - it sounds similar to what you're looking for.

You can read about it here: https://github.com/Club-Seiden/RelicPackageManager/wiki/Getting-your-project-onto-GitHub

Hopefully this'll help. If you have any requests for this program, either let me know or feel free to add it yourself. :smile:

**Comment by ChrisHird** [comment]
Liam, yes probably what I am looking for but did not work at all when I ran against the FTPCLTOSS source lib! Couple of issues, first the record length in my files is not set to 112. You need to account for this when copying source. 2 The source members were not added due to message CPF325E, it left open commit cycles somehow?

`                         Additional Message Information                         
                                                                                
 Message ID . . . . . . :   CPF325E       Severity . . . . . . . :   40         
 Message type . . . . . :   Diagnostic                                          
 Date sent  . . . . . . :   06/23/16      Time sent  . . . . . . :   08:46:30   
                                                                                
 Message . . . . :   Uncommitted changes pending for file MEMBERS in library    
   QT105501.                                                                  
 Cause . . . . . :   Uncommitted changes are pending for file MEMBERS in        
   library QT105501 for commitment definition MEMBERS.                        
 Recovery  . . . :   Do one of the following and try your request again:        
     -- Complete the commitment control process by doing a commit or rollback   
   for commitment definition MEMBERS.                                           
     -- Change the commitment control option and compile the program again.     
 Technical description . . . . . . . . :   The commitment definition identifier 
   is X'100101000000000AAC6B'.                                                  
     The job that initiated the change(s) is 105501/CHRISH/CHRIS#PHE1.          
     The logical unit of work identifier is APPN.SHIELD6.X'8ECDBE759C1D'.00001. 
                                                                        More... 
 Press Enter to continue.                                                       
                                                                                `
3. The program did not pick up just PF-SRC, it also picked up PF-DTA.

Would also be nice to have a command front end and as before allow the IFS root to be set by the user.

Chris...

**Comment by WorksOfBarry** [comment]
Few things I picked up:

1. Detect the record length for the source physical files when creating the build file
2. Find out what is causing CPF325E on the MEMBERS *outfile
3. Only use PF-SRC and not PF-DTA
4. Add a parameter to specify where the source is going to be created

Sound good to you? :)

**Comment by ChrisHird** [comment]
Create command for front end? Would also like to see some context sensitive help built in :-) sorry but I dislike jumping back to the GitHub Repo just to find out what should be happening.. If you need help determining any of the above I can assist, we replicate objects so a lot of the info you need we have to collect for our replication software.

**Comment by WorksOfBarry** [comment]
I edited the previous post to add '5 - create a command for SYNC' :)

Thanks,
Liam

**Comment by WorksOfBarry** [comment]
SYNC is being removed.
