### ISSUE TITLE
Set default library for BUILD

### ISSUE THREAD

**Issue by ChrisHird** [OSSILE/RelicPackageManager#42]
Add a default to BUILD program so it will automatically create the library #RELIC and install into there if no parameter is passed.

**Comment by WorksOfBarry** [comment]
@ChrisHird This has been implemented.

If the parameter on `RBLD` is blank, it will default to `#RELIC` and try to create it if it does not exist.

https://github.com/OSSILE/RelicPackageManager/commit/27068bf656da632ee3ba3600482fe9e5aea5702a
